### PR TITLE
Keep LICENSE lines 80 columns wide

### PR DESCRIPTION
**Pull request by hugopl**
So the license can be show in UI using elorest/compiled_license shard.

### CODE REVIEW

**Comment by jhass** [comment]
Eh,  I'd argue whatever  needs it  80 columns wide should reformat it. But whatever, doesn't harm I guess.

**Comment by hugopl** [comment]
The problem is seem when using:
```Crystal
Gtk::AboutDialog.new(license: Compiled::License.display)
```
This `Compiled::License` is from the shard that grab all LICENSE files. GtkAboutDialog show the licenses without wordwrap, so the window get larger than the entire desktop. I missed this info on the report, sorry :-).

**Comment by jhass** [comment]
yeah, so `Compiled::License.display.gsub(/(?<=^[^\n]{80})/, "\n")` or something like that.

**Comment by hugopl** [comment]
> yeah, so `Compiled::License.display.gsub(/(?<=^[^\n]{80})/, "\n")` or something like that.

But this string processing would waste several **unnoticeable** nano seconds on a code path that is rarely executed :-P, unless using a macro to process the `License.display` macro result.

**Comment by jhass** [comment]
Just saying I wish you a lot  of  fun  with this kind of pull request to all the things your app may ever depend on :P

**Pull request merged**
